# This docker-compose is meant for development only
version: "3"

services:
  database:
    image: postgres:12.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports: 
      - 5432:5432
  redis:
    image: redis:6.0.5
    ports: 
      - 6379:6379
  application:
    build: .
    restart: on-failure
    depends_on: 
      - database
      - redis
    ports: 
      - 8080:8080